/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.Lists;

import java.util.List;


/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./hw01-gradle/build/libs/gradleHelloWorld-0.1.jar
 *
 * To unzip the jar:
 * unzip -l ./hw01-gradle/build/libs/hw01-gradle.jar
 * unzip -l ./hw01-gradle/build/libs/gradleHelloWorld-0.1.jar
 *
 */
public class HelloOtus {
    public static void main(String... args) {
        List<Integer> example = Lists.newArrayList(1, 3, 5);
        System.out.println(example);
    }
}
