spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd

cash:
  schedulingEnabled: true
  schedule:
    blacklist:
      fixedDelay: PT10M
    whitelist:
      fixedDelay: PT10M


countAttempt:
  login: 10
  password: 100
  ip: 1000

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
